FROM mustafahusain/hyperledger-areas-agent:latest

ENV ENABLE_PTVSD 0
ENV ENABLE_PYDEVD_PYCHARM 0
ENV PYDEVD_PYCHARM_HOST "host.docker.internal"

# Add and install demo code
COPY runner/crowdpoint.py ./demo/
